---
# tasks/setup.yml

- name: Deploy | Try to get web server group name
  shell: "ps axo user,group,comm | egrep '(apache|httpd)' | grep -v ^root | uniq | cut -d ' ' -f 2"
  register: deploy_www_owner_group
  changed_when: false
  become: yes

- name: Deploy | Check web server group name
  fail: msg="Could not get web server owner group name!"
  when: deploy_www_owner_group.stdout == ''

- name: Deploy | Set application owner group name
  set_fact:
    deploy_www_owner_group: "{{ deploy_www_owner_group.stdout }}"

- name: Deploy | Set application owner user name
  set_fact:
    deploy_www_owner_user: "{{ ansible_env.USER }}"
